# -*- coding: utf-8 -*-
"""RandomForest.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yC1yU9xJLPsglqW54xXXaNfY5MDuYa13
"""

# import all the libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

df=pd.read_csv("/content/pima-indians-diabetes.data.csv")
df.head()











